import { report } from './lib.mjs';
import { check as emoji } from './check-no-emoji.mjs';
import { check as units } from './check-units.mjs';
import { check as boundaries } from './check-boundaries.mjs';
import { check as tokens } from './check-tokens.mjs';
import { check as imports } from './check-imports.mjs';
import { check as hooks } from './check-hooks.mjs';
import { check as build } from './check-build.mjs';
import { check as longpress } from './check-longpress.mjs';
import { check as dead } from './check-dead.mjs';
import { check as promptTone } from './check-prompt-tone.mjs';
import { check as uiTone } from './check-ui-tone.mjs';
import { check as calls } from './check-calls.mjs';
import { check as backupAll } from './check-backup.mjs';
import { check as contract } from './check-contract.mjs';

console.log('小手机 自检\n');
let failed = 0;
failed += report('视口单位（只用 vh）', units());
failed += report('零 emoji', emoji());
failed += report('导入导出', imports());
failed += report('hook 顺序', hooks());
failed += report('模块边界', boundaries());
failed += report('设计令牌', tokens());
failed += report('长按禁选', longpress());
failed += report('提示词是书面语', promptTone());
failed += report('界面文案是书面语', uiTone());
failed += report('接口调用次数', calls());
failed += report('备份完整性', backupAll());
failed += report('美化契约', contract());
failed += report('死导出', dead());
failed += report('构建号', build());
console.log(failed ? `\n${failed} 项未通过` : '\n全部通过');
process.exit(failed ? 1 : 0);
